package sk.host.arabasso;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

/**
 * Created by arabasso on 29/10/2016.
 */
public class SimplexJanela extends JFrame {
    private JLabel foLabel;
    private JTextField foTextField;
    private JTextArea restricoesTextArea;
    private JLabel restricoesLabel;
    private JButton resolverButton;
    private JTabbedPane solucaoTabbedPane;
    private JTextArea variaveisBasicastextArea;
    private JTextArea variaveisNaoBasicastextArea;
    private JTextArea valorZTextArea;
    private JTextArea passoTextArea;
    private JLabel variaveisBasicasLabel;
    private JLabel variaveisNaoBasicasLabel;
    private JLabel valorZLabel;
    private JPanel simplexPanel;

    public SimplexJanela(String title) throws HeadlessException {
        super(title);

        setMinimumSize(new Dimension(900, 700));
        setLocationRelativeTo(null);
        getContentPane().add(simplexPanel);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        resolverButton.addActionListener(this::resolverButtonClick);
    }

    private void resolverButtonClick(ActionEvent e){
        String fo = foTextField.getText();
        String restricoes = restricoesTextArea.getText();

        SimplexConstrutor construtor = new SimplexConstrutor();

        Simplex simplex = construtor.construir(fo, Arrays.asList(restricoes.split("\n")));

        SimplexSolucao solucao = simplex.solucao();

        passoTextArea.setText(solucao.texto(simplex.variaveis));

        while (!solucao.otima) {
            simplex = simplex.proximoAlgoritmo();

            solucao = simplex.solucao();

            passoTextArea.append("\n");
            passoTextArea.append(solucao.texto(simplex.variaveis));
        }

        variaveisBasicastextArea.setText(solucao.variaveisBasicasTexto(simplex.variaveis));
        variaveisNaoBasicastextArea.setText(solucao.variaveisNaoBasicasTexto(simplex.variaveis));
        valorZTextArea.setText(solucao.valorZTexto());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        simplexPanel = new JPanel();
        simplexPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 3, new Insets(10, 10, 10, 10), -1, -1));
        simplexPanel.setMinimumSize(new Dimension(600, 500));
        simplexPanel.setPreferredSize(new Dimension(600, 500));
        foLabel = new JLabel();
        foLabel.setText("F.O.");
        simplexPanel.add(foLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        foTextField = new JTextField();
        foTextField.setText("4X1 + 3X2 + 2X3 + X4");
        simplexPanel.add(foTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        restricoesLabel = new JLabel();
        restricoesLabel.setText("Restrições");
        simplexPanel.add(restricoesLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        solucaoTabbedPane = new JTabbedPane();
        simplexPanel.add(solucaoTabbedPane, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 400), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        solucaoTabbedPane.addTab("Solução", panel1);
        variaveisBasicasLabel = new JLabel();
        variaveisBasicasLabel.setText("Variáveis básicas");
        panel1.add(variaveisBasicasLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        variaveisNaoBasicasLabel = new JLabel();
        variaveisNaoBasicasLabel.setText("Variáveis não básicas");
        panel1.add(variaveisNaoBasicasLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        valorZLabel = new JLabel();
        valorZLabel.setText("Valor Z");
        panel1.add(valorZLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        variaveisNaoBasicastextArea = new JTextArea();
        variaveisNaoBasicastextArea.setEditable(false);
        panel1.add(variaveisNaoBasicastextArea, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        valorZTextArea = new JTextArea();
        valorZTextArea.setEditable(false);
        panel1.add(valorZTextArea, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        variaveisBasicastextArea = new JTextArea();
        variaveisBasicastextArea.setEditable(false);
        panel1.add(variaveisBasicastextArea, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        solucaoTabbedPane.addTab("Passo-a-passo", panel2);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        passoTextArea = new JTextArea();
        passoTextArea.setEditable(false);
        scrollPane1.setViewportView(passoTextArea);
        restricoesTextArea = new JTextArea();
        restricoesTextArea.setRows(3);
        restricoesTextArea.setText(" X1 + X2  + X3  + X4 <= 120\n2X1 + X2  + 3X3 - X4 <= 260\n X1 + 2X2 + 2X3 + X4 <= 180");
        simplexPanel.add(restricoesTextArea, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        resolverButton = new JButton();
        resolverButton.setText("Resolver");
        simplexPanel.add(resolverButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        simplexPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        simplexPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return simplexPanel;
    }
}
